#!/bin/bash

# Baper - Make Beautifull terminal 
# Codename  : Jones
# Version   : 1.0
# Author    : alinko (shutdown57)
# Site      : linuXcode.org


m="\e[1;31m" # merah
k="\e[1;33m" # kuning kyak tai
h="\e[1;32m" # Hijau 
b="\e[1;34m" # Biru
n="\e[1;0m"  # default
u="\e[4m"    # underlined 
clear
BAPER_WORK_DIR="/home/kagari/baper/coli"
case $1 in
	"--ahh" )
cat $BAPER_WORK_DIR/$2.txt > /dev/null 2>&1
if [[ "$?" -eq "0" ]]; then
	cat $BAPER_WORK_DIR/$2.txt
	printf "\n\n"
else
	echo "BAPER GAN? : File Not Found.."
fi
		;;
	"--add" )
cat $2 > /dev/null 2>&1
if [[ "$?" -eq "0" ]]; then
	cp $2 $BAPER_WORK_DIR
else
	echo "BAPER GAN? : File Not Found.."
fi        ;;
     "--figlet" )
which figlet > /dev/null 2>&1
if [[ "$?" -eq "0" ]]; then
	figlet $2
else
	echo "BAPER GAN? : figlet Not installed."
fi
          ;;
          "--show" )
ls $BAPER_WORK_DIR
          ;;
     "--cpuinfo" )
cat /proc/cpuinfo > /dev/null 2>&1
if [[ "$?" -eq "0" ]]; then
	more /proc/cpuinfo
else
	echo "/proc/cpuinfo : Not Found ."
fi
         ;;
     * )
clear
      printf "

            ▄▄▄▄    ▄▄▄       ██▓███  ▓█████  ██▀███  
            ▓█████▄ ▒████▄    ▓██░  ██▒▓█   ▀ ▓██ ▒ ██▒
            ▒██▒ ▄██▒██  ▀█▄  ▓██░ ██▓▒▒███   ▓██ ░▄█ ▒
            ▒██░█▀  ░██▄▄▄▄██ ▒██▄█▓▒ ▒▒▓█  ▄ ▒██▀▀█▄  
            ░▓█  ▀█▓ ▓█   ▓██▒▒██▒ ░  ░░▒████▒░██▓ ▒██▒
            ░▒▓███▀▒ ▒▒   ▓▒█░▒▓▒░ ░  ░░░ ▒░ ░░ ▒▓ ░▒▓░
            ▒░▒   ░   ▒   ▒▒ ░░▒ ░      ░ ░  ░  ░▒ ░ ▒░
             ░    ░   ░   ▒   ░░          ░     ░░   ░ 
             ░            ░  ░            ░  ░   ░     
             ░
"

echo -e $k"+"$n"-------------------------------------------------------------------"$k"+"$n
echo -e $k"+"$n"    $m  Codename                   :   $h         Jones.               "$k"+"$n
echo -e $k"+"$n"    $m  Version                    :   $h         1.0                  "$k"+"$n
echo -e $k"+"$n"    $m  Author                     :   $h         alinko (shutdown57)  "$k"+"$n
echo -e $k"+"$n"    $m  Site                       :   $h         linuXcode.org        "$k"+"$n
echo -e $k"+"$n"-------------------------------------------------------------------"$k"+"$n
printf "
USAGE (MENGGUNAKAN :p)

baper --ahh <BaperFiles>
baper --add <BaperFiles>
baper --show
baper --figlet \"KataKataBaper\"
baper --about
baper --cpuinfo

      "
      ;;
esac