#!/bin/bash
k="\033[1;33m"
m="\033[1;31m"
h="\033[1;32m"
b1(){
echo -e $k"                     (+++++++++++)                                                       "
echo -e $k"                  (++++)                                                                 "
echo -e $k"               (+++)                                                                     "
echo -e $k"             (+++)                                                                       "
echo -e $k"            (++)                                                                         "
echo -e $k"            [~]                                                                          "
echo -e $k"            | | (~)  (~)  (~)    /~~~~~~~~~~~~                                           "
echo -e $k"         /~~~~~~~~~~~~~~~~~~~~~~~  [~_~_] |    * * * /~~~~~~~~~~~|                       "
echo -e $k"       [|  %___________________           | |~~~~~~~~            |                       "
echo -e $k"         \[___] ___   ___   ___\  No. 4   | |   IKLAN LEWAT      |                       "
echo -e $k"      /// [___+/-+-\-/-+-\-/-+ \\_________|=|____________________|=  NEtNoott....        "
echo -e $k"    //// @-=-@ \___/ \___/ \___/  @-==-@      @-==-@      @-==-@                         "
echo -e $k" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   "

}
b2(){
echo -e $k"                                (+++++++++++)                                                       "
echo -e $k"                             (++++)                                                                 "
echo -e $k"                          (+++)                                                                     "
echo -e $k"                        (+++)                                                                       "
echo -e $k"                       (++)                                                                         "
echo -e $k"                       [~]                                                                          "
echo -e $k"                       | | (~)  (~)  (~)    /~~~~~~~~~~~~                                           "
echo -e $k"                    /~~~~~~~~~~~~~~~~~~~~~~~  [~_~_] |    * * * /~~~~~~~~~~~|                       "
echo -e $k"                  [|  %___________________           | |~~~~~~~~            |                       "
echo -e $k"                    \[___] ___   ___   ___\  No. 4   | |   IKLAN LEWAT      |                       "
echo -e $k"                 /// [___+/-+-\-/-+-\-/-+ \\_________|=|____________________|=  NEtNoott....        "
echo -e $k"               //// @-=-@ \___/ \___/ \___/  @-==-@      @-==-@      @-==-@                         "
echo -e $k"            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   "

}
b3(){
echo -e $k"                                             (+++++++++++)                                                       "
echo -e $k"                                          (++++)                                                                 "
echo -e $k"                                       (+++)                                                                     "
echo -e $k"                                     (+++)                                                                       "
echo -e $k"                                    (++)                                                                         "
echo -e $k"                                    [~]                                                                          "
echo -e $k"                                    | | (~)  (~)  (~)    /~~~~~~~~~~~~                                           "
echo -e $k"                                 /~~~~~~~~~~~~~~~~~~~~~~~  [~_~_] |    * * * /~~~~~~~~~~~|                       "
echo -e $k"                               [|  %___________________           | |~~~~~~~~            |                       "
echo -e $k"                                 \[___] ___   ___   ___\  No. 4   | |   IKLAN LEWAT      |                       "
echo -e $k"                              /// [___+/-+-\-/-+-\-/-+ \\_________|=|____________________|=  NEtNoott....        "
echo -e $k"                            //// @-=-@ \___/ \___/ \___/  @-==-@      @-==-@      @-==-@                         "
echo -e $k"                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   "

}
	clear
	b3
	sleep 1
	clear
	b2
	sleep 1
	clear
	b1
	sleep 1
	clear
	b1
	sleep 1
	clear
	b2
	sleep 1
	clear
	b3 
	sleep 1

echo "~[ welcome! This Script Installer For baper v1.0 ]~"
echo "~ Select your options :"
printf "\n\n"
echo "1 ) Install"
echo "2 ) Uninstall"
printf "\n\n"
echo "+----------------------------------+"
echo -n $m"options ] :"$n
read opt
if [[ $opt == "1" ]]; then
echo -e $h"[+] Installing please wait..."$n
cp baper /usr/bin
sleep 1
echo -e $h"[+] Creating directory '/opt/baper' ..."$n
mkdir /opt/baper
sleep 1
mkdir /opt/baper/coli
echo -e $h"[+] Copying files ..."$n
cp coli/* /opt/baper/coli
sleep 1
echo -e $h"[+] Finishing ..."$n
cp install /opt/baper
sleep 1
echo -e $h"[+] FINISHED [+]"$n
elif [[ $opt == "2" ]]; then
	echo -e $m"[+] Removing /usr/bin/baper ..."$n
	rm /usr/bin/baper
	sleep 1
	echo -e $m"[+] Removing Files.."$n
	rm /opt/baper/coli/*
	sleep 1
	echo -e $m"[+] Removing directory '/opt/baper' .. "$n
	rmdir /opt/baper/coli
	rm /opt/baper/*
	rmdir /opt/baper
	sleep 1
	echo -e $m"[+] UNINSTALL FINISHED [+]"$n
